version: '3'
services:
    postgres:
        image: 'postgres:lastest'
    redis:
        image: 'redis:lastest'
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports: 
            - '3000:5000'
        volumes:
            - /app/node_modules
            - ./server:/app


        