version: '3'
services:
    postgres:
        image: postgres
    redis:
        image: redis
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports: 
            - '3000:5000'
        volumes:
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST = redis
            - REDIS_PORT = 6379   #default port created by the image
            - PGUSER = postgres  #this is the default user created by the image
            - PGHOST = postgres
            - PGDATABASE = postgres  #this is the default database created by the image
            - PGPASSWORD = postgres_password #this is the default password created by the image
            - PGPORT = 5432    #defaul port created by the image



    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:app
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST = redis
            - REDIS_PORT = 6379   
        