version: '3'
services:
    postgres:
        image: postgres
    redis:
        image: redis
    nginx:
        restart: always    #this is a server, it must be always on!
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '4000:80'
        depends_on: 
            - api
            - client
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379   #default port created by the image
            - PGUSER=postgres  #this is the default user created by the image
            - PGHOST=postgres
            - PGDATABASE=postgres  #this is the default database created by the image
            - PGPASSWORD=postgres_password #this is the default password created by the image
            - PGPORT=5432    #defaul port created by the image
        depends_on: 
            - postgres
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379   
        